#include: package:lint/analysis_options.yaml
#include: package:effective_dart/analysis_options.1.2.0.yaml
#include: package:lints/recommended.yaml
#include: package:flutter_lints/flutter.yaml
#include: package:lint/analysis_options_package.yaml
